Aiven-Open/pglookout

pglookout/current_master.py

Following the lines of 6e4ce4d, fix also current_master entry point.

pglookout: Fix broken main() entry point for current_master

---

debian/control
pglookout/current_master.py
pglookout/pglookout.py

This happens at least with python 2.6.6:
After the change 8816adbbb, pglookout stopped working with Python 2.6 as
json behaves slightly differently when compared to simplejson. Namely,
json library converts all strings to unicode whereas simplejson left strings
as str if the whole input is ASCII only. I believe this is an issue many
have faced with simplejson: https://code.google.com/p/simplejson/issues/detail?id=40
To make it work, prefer simplejson over json when it is available.
This should prevent following tracebacks:
2015-01-26 18:28:47,551pglookoutDEBUGLoading JSON config from: '/etc/pglookout/pglookout.json', signal: None, frame: None
Traceback (most recent call last):
File "/usr/bin/pglookout", line 9, in <module>
load_entry_point('pglookout==1.0.0', 'console_scripts', …

pglookout: prefer simplejson over json, if simplejson is available

---

.travis.yml
Makefile
pglookout.spec
pglookout/pglookout.py

Also, run pylint from `pylint.lint` instead of `pylint` for compatibility
and drop an unnecessary pylint disable for W0713 which didn't work on CentOS
7's pylint.

rpm: Build just a single package using Python 3 if possible

---

.pylintrc
pglookout/pglookout.py

Pylint 1.4.3 dropped the star-magic warning and disabling it in code
comments now causes a new warning.  Disable it in the RC file instead to
disable it the check on old versions and ignore it on the new ones.

pylint: disable W0142 (star-magic) in rc file to support newer pylint versions

---

pglookout/common.py
pglookout/pglookout.py
test/test_common.py
test/test_lookout.py

If we don't see a master node in the cluster before failover_timeout seconds
have passed since the list of cluster nodes was last refreshed perform a
failover to promote one of the standby nodes.  This is useful when a cluster
has been brought up from backups and there is no existing master node.
If a master node has been present in the cluster and later on disappears
from both connections and configuration we should perform an immediate
failover decision as there is no chance of reconnecting to a node that's no
longer in our configuration.  This speeds up promotion when a node is
deleted from the cluster.

failover: perform failover if master node disappears or never appears

---

test/test_lookout.py

Each test case creates a temporary directory for storing a statefile +
optionally some other things; previously we only ever deleted the statefile
but would leave the directory behind.  Let's wipe the entire directory tree
at teardown and prefix it with something that makes it easy to recognize if
it gets left behind because of a failure.
In Python 3 we could use tempfile.TemporaryDirectory, but unfortunately
that's not available on Python 2 which we still support.

tests: wipe the temporary directory at teardown

---

.pylintrc
pglookout/cluster_monitor.py
pglookout/common.py
pglookout/current_master.py
pglookout/pglookout.py
pglookout/webserver.py
test/test_cluster_monitor.py
test/test_common.py
test/test_lookout.py

Plus refactoring and a few minor fixes.

timestamps: fix second calculation between datetime objects

---

pglookout/pglookout.py
test/test_lookout.py

If there are multiple nodes with the same replication positions pick the one
with the "highest" name to make sure pglookouts running on all standbys make
the same decision.  The rationale for picking the "highest" node is that
there's no obvious way for pglookout to decide which of the nodes is "best"
beyond looking at replication positions, but picking the highest id supports
environments where nodes are assigned identifiers from an incrementing
sequence identifiers and where we want to promote the latest and greatest
node.  In static environments node identifiers can be priority numbers, with
the highest number being the one that should be preferred.

failover: select the furthest replicated node with the highest identifier

---

Makefile

Allows replacing e.g. python-urllib3 with python2-urllib3

makefile: dnf --allowerasing for dependencies

---

.travis.yml
test/conftest.py
test/test_cluster_monitor.py
test/test_lookout.py
test/test_webserver.py

Also try to make sure we shut down the webserver at the end of each test
case.

tests: use pytest and fixtures instead of unittest.TestCase

---

pglookout.spec

We had a dependency on postgresql-server to be able to create an empty
/var/lib/pglookout which is owned by the postgres user.  This may have been
convenient, but not really necessary as a user will have to manually set up
configuration and state anyway, so let's drop it to avoid needing a hard
dependency on postgresql-server.

rpm spec: remove dependency on postgresql-server

---

pglookout/cluster_monitor.py
pglookout/pglookout.py
pglookout/webserver.py
test/test_cluster_monitor.py
test/test_webserver.py

This is to allow HTTP based requests to make an immediate request
to check the cluster status and to do an immediate failover decision.

web: Add POST /check endpoint for immediate clustermonitor check

---

README.rst
pglookout.json
pglookout/pglookout.py
test/test_lookout.py

If current master disappeared from configuration promotion was not
performed until a timeout was exceeded, presumably to guard against
situations where node goes missing from config due to some fluke and
is very soon put back into configuration.
In case of controlled removal of old master the master can be known to
be gone and not coming back for sure. Allow indicating such situation
in pglookout configuration so that gracefully terminated old master can
be replaced immediately.

Allow marking a node as "known to be gone"

---

pglookout.spec

Fedora 31 comes with an updated rpmbuild that is more picky about what
it will accept. The %{requires} macro is no longer accepted in the
BuildRequires field.

pglookout.spec: support building on Fedora 31

---

Makefile

pylint cannot be found on Fedora 33

Makefile: refer to pylint-3

---

pglookout/pglookout.py
test/test_lookout.py

Without this patch warning boundary could be set lower than failover
timeout leading to warning file not created at all. As result warning
handling mechanism never comes into play.
This patch improves that behaviour by setting warning boundary half the
failover timeout.

fix replication lag warning to be always lower that failover timeout

---

README.rst
pglookout/cluster_monitor.py
pglookout/pglookout.py
test/test_cluster_monitor.py
test/test_lookout.py

this key allows the polling of observers only when pglookout notices
that it is in warning mode.
This is useful when the observer is a single entity observing many
different clusters. And in that case pglookout needs to make sure
the db_poll has happened at-least once to retrieve data from observers.
In pglookout's producer-consumer architecture, consumer thread makes
the decision based on polled data. The consumer relies on timeout along
with ping from producer. Because of timeouts the consumer might
accidentally rely on stale data from the producer. And one way to
indicate staleness is when consumer is in warning mode and even though
observers are configured their polling information is not
available/updated.
Once the option is set to True, observers will be polled and in warning
state …

a new key is added to the config: poll_observers_on_warning_only

---

pglookout/pglookout.py

to make sure consumer threads is not looping unnecessarily. This can
happen if the node is loaded and consumer thread has remain unscheduled

clear the decision queue

---

pglookout/cluster_monitor.py
pglookout/pglookout.py

Sometimes the poll_observers_on_warning_only setting was accessed
already before load_config completed, causing KeyError and pglookout
to be left in bad state.

Avoid KeyError if load_config isn't called early enough

---

pglookout/cluster_monitor.py

Since txid_current() can block when using synchronous replication, disable synchronous_commit at all.
We only care about generating a new xid to make sure that WAL is progressing, not that it makes its way to the standby.

Use synchronous_commit to off

---

version.py

Package build failure on fedora 39, seen below:
```
[2024-01-21T10:54:07.962Z] + python3 setup.py install --root=/srv/jenkins/workspace/aiven-deps-mb-f38-x86_64_main/rpmbuild/BUILDROOT/pglookout-2.0.2-11.fc39.x86_64
[2024-01-21T10:54:07.962Z] Traceback (most recent call last):
[2024-01-21T10:54:07.962Z]   File "/srv/jenkins/workspace/aiven-deps-mb-f38-x86_64_main/rpmbuild/BUILD/pglookout-028ba9e6002c8a50c6c7f8147ab02620e12f12f7/setup.py", line 4, in <module>
[2024-01-21T10:54:07.962Z]     import version
[2024-01-21T10:54:07.962Z]   File "/srv/jenkins/workspace/aiven-deps-mb-f38-x86_64_main/rpmbuild/BUILD/pglookout-028ba9e6002c8a50c6c7f8147ab02620e12f12f7/version.py", line 9, in <module>
[2024-01-21T10:54:07.962Z]     import imp
[2024-01-21T10:54:07.962Z] ModuleNotFoundError: No module …
```

fix import error version.py for fedora 39 [SRE-7997]

---

pglookout/pglookout.py

When SIGHUP is sent during `load_config` it's possible that `config_reload_pending` will be set to `False` (thus overwriting the `True` value, which was set in signal handler) and new reload won't happen.

Fix a potential issue with race condition when reloading a config

---

pglookout/pglookout.py
test/conftest.py

When we notice the primary node has gone, we need to get up to date information from the other standby nodes if needed.

Decide to failover based on uptodate info

---

README.rst
pglookout/pglookout.py
pyproject.toml
test/test_lookout.py
test/utils.py

Support explicit prioritization between instances. This can be configured via ``failover_priorities`` key, and will be consulted upon picking up the standby that should do the promotion in cases where multiple nodes have a matching replication position.
Previously, and also as the current default, the selection was based on the sorting order of the remote nodes.
The configuration option allows some additional flexibility, and supports e.g. topologies where we have more favorable and less desirable standbys in multiple different network locations.

pglookout: support explicit failover priorities
